name: Homebrew Livecheck

on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  livecheck:
    name: Livecheck
    runs-on: macos-26

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v7

    - name: Bump Homebrew Casks
      uses: kitschpatrol/github-action-homebrew-bump-cask@v3.8.8
      with:
        token: ${{ secrets.HOMEBREW_TOKEN }}
        message: Bump version of homebrew cask
        tap: nepherte/ffmpeg
        livecheck: true
